# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_development', 'В разработке'), ('close', 'Закрыта'), ('cancel', 'Отменено')], default='new', max_length=50),
        ),
    ]
